### ISSUE TITLE
Support go1.19 build

### ISSUE THREAD

**Issue by chenrui333** [brevdev/brev-cli#154]
Currently, it does not build with go1.19, the error log is as below:

```
package github.com/brevdev/brev-cli
	imports github.com/brevdev/brev-cli/pkg/cmd
	imports github.com/brevdev/brev-cli/pkg/cmd/login
	imports github.com/brevdev/brev-cli/pkg/server
	imports github.com/brevdev/brev-cli/pkg/vpn
	imports github.com/brevdev/brev-cli/pkg/vpn/tailscaled
	imports tailscale.com/wgengine/netstack
	imports inet.af/netstack/tcpip
	imports inet.af/netstack/atomicbitops
	imports inet.af/netstack/state
	imports inet.af/netstack/state/wire
	imports inet.af/netstack/gohacks: build constraints exclude all Go files in /Users/rui/Library/Caches/Homebrew/go_mod_cache/pkg/mod/inet.af/netstack@v0.0.0-20211120045802-8aa80cf23d3c/gohacks
```

relates to https://github.com/Homebrew/homebrew-core/pull/115784

**Comment by r33drichards** [comment]
Hey thanks for the headsup, this is the fix ? https://github.com/Homebrew/homebrew-core/blob/master/Formula/brev.rb#L23

**Comment by r33drichards** [comment]
should be fixed with [support go 1.19 (rm tailscale)](https://github.com/brevdev/brev-cli/commit/2f63e5d2c6a5cebebbe8351353bc4ddc768adc76) I issued another release, is there a way for me to trigger brew build bot?

**Comment by chenrui333** [comment]
I can trigger a new run.

**Comment by chenrui333** [comment]
> Hey thanks for the headsup, this is the fix ? https://github.com/Homebrew/homebrew-core/blob/master/Formula/brev.rb#L23

yeah, that would be the fix.

**Comment by chenrui333** [comment]
Worked out in my local, closing this issue, thanks for the quick turnaround!
